### ISSUE TITLE
Please provide a persistent identifier for https://github.com/klb2/qmkpy-datasets

### ISSUE THREAD

**Issue by ulf1** [klb2/qmkpy#10]
In your paper https://github.com/klb2/qmkpy/blob/joss-paper/paper/paper.md you added the hyperlink to https://github.com/klb2/qmkpy-datasets what is not a persistent identifier. Please consider syncing https://github.com/klb2/qmkpy-datasets with Zenodo or similar services.

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718
