### ISSUE TITLE
State of the field - Please other software that deals with QKP problems or related problems

### ISSUE THREAD

**Issue by ulf1** [klb2/qmkpy#11]
In your paper https://github.com/klb2/qmkpy/blob/joss-paper/paper/paper.md you should mention other software. Think of it as a literature review to find their drawbacks that are fixed by your software.

1. What other software for QKP exists? (Is there anything in Gurobi, SCIP, CPLEX, or some old papers with super old F or C code?)
2. What are today's or your software requirements (e.g., you are targeting python users, you need an OSS licensed software, adaptability for new algorithm ideas)
3. Write your paper text

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718

**Comment by max-little** [comment]
See https://github.com/klb2/qmkpy/issues/18
