### ISSUE TITLE
Errors/problems in mathematical descriptions

### ISSUE THREAD

**Issue by max-little** [klb2/qmkpy#12]
In the doc welcome page and in the readme.md, the following needs fixing/clarification:
- Are the p_i and p_ij, positive integers or positive reals? Or, are there no restrictions on these values?
- Similar comment on the weight capacities c_u, and the weights w_i?
- u in the set script K; we assume K is some set of indices? Is this set finite?
- i in sets script A_u -- we assume these are indexed sets of indices? Finite?
- If i comes from script A_u, then are the values in the A_u different for different u's in script K? Otherwise, it seems that the profits p_i are somehow shared between knapsacks? Is this intentional? In which case, why are there separate joint profits p_ij?
- Similarly for the w_i: is there just one set of weights indexed by the values in A_u? In which case weights are shared among knapsacks?
- In the final summation in the constraint, the limits should just be u in script K, as it is with the other summations?
- Since the a_iu are zero-one values, actually, this package only addresses zero-one knapsack problems, rather than integer knapsack problems, right? In which case, this should be made clear in the title, description of the package etc.
- The readme.md and the doc welcome page use different notation e.g. A(u) rather than A_u, this should be made consistent across the entire documentation.
- The explanation for the variables in the mathematical description in the readme.md are entirely missing and need to be included.
- In the readme.md, the description under the equations is wrong, it should have script K rather than K.
- In both doc welcome page and readme.md: write forall i in 1,2,..,N rather than forall 1<=i<=N.

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718
