### ISSUE TITLE
Improve description of the package.

### ISSUE THREAD

**Issue by max-little** [klb2/qmkpy#13]
It isn't really made sufficiently clear the purpose of this package. It is not a package for solving the zero-one QMKP per se, rather, it is a package containing a _testbed_ for developing novel zero-one QMKP solver algorithms. This needs to be made much clearer, in the paper, the readme, and the documentation.

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718

**Comment by max-little** [comment]
See https://github.com/klb2/qmkpy/issues/18
