### ISSUE TITLE
Very "thin" review of the area e.g. missing exact solver examples?

### ISSUE THREAD

**Issue by max-little** [klb2/qmkpy#17]
The paper review is pretty shallow on this extensive topic, e.g. just a simple search on Wikipedia provides multiple references and pointers:
https://en.wikipedia.org/wiki/Quadratic_knapsack_problem

For instance, as with the standard knapsack, there are exact (quasi-polynomial time) dynamic programming and branch-and-bound methods. It would be very helpful to review these in the paper and provide an example implementation, for comparison.

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718

**Comment by klb2** [comment]
The mentioned Wikipedia article refers to the quadratic _single_ knapsack problem. Most solution algorithms are not directly applicable to the quadratic _multiple_ knapsack problem that is considered in the QMKPy framework.
We added this remark to the paper in f8ec4a13a84bb8afad697460ad95d4c5e3b506d3.

While many solution algorithms are proposed in the literature, the primary goal of the framework is to provide a testbed environment for researchers and developers working in that area to quickly implement and share their novel solutions.
Therefore, we feel that it is not necessary to provide a comprehensive collection of many algorithms in the initial version of QMKPy. However, there are still already four different algorithms available in version 1.1 for a baseline comparison.
