### ISSUE TITLE
Multi-line latex formula doesn't work in pypi

### ISSUE THREAD

**Issue by ulf1** [klb2/qmkpy#2]
Problem:
- No line breaks in latex formula: https://pypi.org/project/qmkpy/

Cause:
- Multiline latex formular in https://github.com/klb2/qmkpy#problem-description

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718

**Comment by klb2** [comment]
Unfortunately, I was not able to find a solution to this issue so far. The problem appears to be the MathJax version used at pypi. The same formula works fine on GitHub (README) and on ReadTheDocs (index page).

**Comment by ulf1** [comment]
nope. it is not necessary to fix that
