### ISSUE TITLE
Add your Community Guidelines

### ISSUE THREAD

**Issue by ulf1** [klb2/qmkpy#4]
Please add your community guidelines at the end of the README.md
This can be boilerplate stuff.

Address the following:
1) Contribute to the software 
2) Report issues or problems with the software 
3) Seek support

Boilerplate example
```
...
### Contributing
Please contribute using [Github Flow](https://guides.github.com/introduction/flow/). Create a branch, add commits, and [open a pull request](https://github.com/yourname/yourreponame/compare/).
```

**Comment by ulf1** [comment]
You can link your CTAs (call to action) to contribute as well, e.g. https://qmkpy.readthedocs.io/en/latest/developing.html#contributing-a-new-algorithm-to-the-package

**Comment by jbytecode** [comment]
Due to JOSS submission: https://github.com/openjournals/joss-reviews/issues/4718
